#ifndef BASE_H
#define BASE_H

#include "types.h"

#include "Spyro/Code/SE/XSEItemHandler.h"

struct XSEItemHandler_Base : /* 0x000 */ XSEItemHandler
{ // 0x470
    //     static EXRuntimeClass classXSEItemHandler_Base;

    // protected:
    //     /* 0x250 */ u32 m_Type;
    //     /* 0x254 */ u32 m_Hash;
    //     /* 0x258 */ u16 m_Control;
    //     /* 0x25c */ float m_Mass;
    //     /* 0x260 */ SEComms* m_pComms;
    //     /* 0x270 */ EXVector m_Ambient;
    //     /* 0x280 */ EXHashCode m_AnimEvent;
    //     /* 0x284 */ u32 m_AnimEventFlags;
    //     /* 0x288 */ EXItemAnimator* m_pShadow;
    //     /* 0x28c */ float m_ShadowGroundY;
    //     /* 0x290 */ XBits8 m_ShadowCtrl;
    //     /* 0x291 */ s8 m_ShadowLayer;
    //     /* 0x292 */ XBits16 m_MipScaleCtrl;
    //     /* 0x294 */ XBits16 m_harmCtrl;
    //     /* 0x298 */ float m_Charred;
    //     /* 0x29c */ float m_CharredLevel;
    //     /* 0x2a0 */ float m_MipScale;
    //     /* 0x2a4 */ float m_MinMipScale;
    //     /* 0x2a8 */ float m_MaxMipScale;
    //     /* 0x2ac */ float m_MipScaleSpeed;
    //     /* 0x2b0 */ XSEItemHandler_ScriptEffect* m_IceScript;
    //     /* 0x2b4 */ SETime m_FreezeTimer;
    //     /* 0x2bc */ SETime m_ElecTimer;
    //     /* 0x2d0 */ EXVector m_FreezeAmbient;
    //     /* 0x2e0 */ EXVector m_TriggerPosition;
    //     /* 0x2f0 */ EXVector m_TriggerRotation;
    //     /* 0x300 */ EXVector m_oldPosition;
    //     /* 0x310 */ EXVector m_oldRotation;
    //     /* 0x320 */ EXVector* m_ValidTarget;
    //     /* 0x330 */ EXVector m_Target;
    //     /* 0x340 */ EXVector m_TrueTarget;
    //     /* 0x350 */ EXVector3 m_Scale;
    //     /* 0x360 */ BodyCollision BodyColl;
    //     /* 0x3b0 */ EXHashCode m_EntityHash;
    //     /* 0x3b4 */ EXHashCode m_GeoFileHash;
    //     /* 0x3b8 */ SpyroBASIC* m_pBASIC;
    //     /* 0x3bc */ EXTexSwapInfo m_TextureSwap;

    // public:
    //     /* 0x3d0 */ FamilyItem m_Family;
    //     /* 0x3dc */ XODListItem m_Platform;
    //     /* 0x3e8 */ XODListItem m_PlatformList;
    //     /* 0x3f4 */ XODListItem m_Breath;
    //     /* 0x400 */ SiteInfo* m_Site;
    //     /* 0x404 */ SETime m_Immunity;
    //     /* 0x40c */ RCode rcode;
    //     /* 0x410 */ u16 m_PlatformCtrl;
    //     /* 0x414 */ u32 m_Flags;
    //     /* 0x418 */ u32 m_Status;
    //     /* 0x41c */ u32 m_LastAction;
    //     /* 0x420 */ u32 m_Action;
    //     /* 0x424 */ int m_idle_count;
    //     /* 0x428 */ int m_start_idle_count;
    //     /* 0x42c */ int m_idle_delay;
    //     /* 0x430 */ int m_Vunerable;
    //     /* 0x440 */ EXVector LookingAt;
    //     /* 0x450 */ EXItemRender_SkinAnim* m_FlameGlo;
    //     /* 0x454 */ EXItemAnimator_Entity* m_FlameGloEntity;
    //     /* 0x458 */ float m_FlameGlo_Intensity;
    //     /* 0x45c */ float m_FlameGlo_Red;

    // protected:
    //     /* 0x460 */ u32 m_CutSceneHandlerID;

    // public:
    //     XSEItemHandler_Base& operator=();
    //     XSEItemHandler_Base();
    //     /* vtable[4] */ virtual Bool DoUpdate();
    //     /* vtable[3] */ virtual Bool Initialise();

    // protected:
    //     static EXRuntimeClass* _GetBaseClass(/* parameters unknown */);

    // public:
    //     /* vtable[1] */ virtual EXRuntimeClass* GetRuntimeClass();
    //     Bool IsKindOf();
    //     char* ClassName();
    //     static XSEItemHandler_Base* CreateObject(/* parameters unknown */);
    //     static XSEItemHandler* new_XSEItemHandler(/* parameters unknown */);
    //     void StartEXStats();
    //     void StopEXStats();
    //     float GetEXStatsMilliSecs();
    //     float GetEXStatsMilliSecsAv();
    //     float GetEXStatsMilliSecsMax();
    //     EXTimer* GetEXStats();
    //     XSEItemHandler_Base();
    //     /* vtable[2] */ virtual XSEItemHandler_Base(XSEItemHandler_Base*, int, void);
    //     XItemPhysics* GetItemPhysics();
    //     EXVector GetItemPosition();
    //     void SetItemPosition();
    //     EXVector GetItemRotation();
    //     void SetItemRotation();
    //     void ZeroControl();
    //     void Control();
    //     void SetControl();
    //     void ClrControl();
    //     u16 Control();
    //     u16 TestControl();
    //     void ZeroStatus();
    //     void Status();
    //     void SetStatus();
    //     void ClrStatus();
    //     u16 Status();
    //     u16 TestStatus();
    //     void Type();
    //     u32 Type();
    //     void Hash();
    //     u32 Hash();
    //     void Mass();
    //     float Mass();
    //     /* vtable[33] */ virtual char* GetName();
    //     EXHashCode GetFileHash();
    //     void KillMe();
    //     EXVector Target();
    //     Bool ValidTarget();
    //     void SetTarget();
    //     void ClearTarget();
    //     void SetPlayerAsTarget();
    //     void SetHomeAsTarget();
    //     /* vtable[34] */ virtual void PlayerPos();
    //     void SparxPos();
    //     /* vtable[35] */ virtual float FacePlayer();
    //     /* vtable[36] */ virtual float FacePlayerNow();
    //     void SetTargetPos();
    //     float FaceTargetFront();
    //     float FaceTargetFrontNow();
    //     float FaceTargetNow();
    //     float FaceTarget();
    //     float FaceForward();
    //     float GetTargetAngle();
    //     float GetTargetAngle();
    //     float GetTargetAngleY();
    //     float GetTargetRange();
    //     float GetTargetRange();
    //     float DistFromHome();
    //     void CopyTriggerPos();
    //     void CopyOld();
    //     u32 IsOnPlatform();
    //     void AttachPlatform();
    //     void UnattachPlatform();
    //     XSEItemHandler* FindNearest();
    //     void UpdateGroups();
    //     void AddGroups();
    //     void RemoveGroups();
    //     void Remove();
    //     void RemoveFromFamily();
    //     void AdoptFamilyChild();
    //     void AdoptFamilyParent();
    //     EXItemAnimator* AddAnimatorImplicit();
    //     EXItemAnimator* AddAnimator();
    //     void ChangeAnimSkin();
    //     void ChangeAnim();
    //     void ChangeAnim();
    //     EXRotOrder GetStrippedData();
    //     EXRotOrder GetStrippedData();
    //     EXRotOrder ApplyStrippedData();
    //     EXRotOrder ApplyStrippedData();
    //     void CheckModeChange();
    //     void ForceModeChange();
    //     void SetupDepthPtr();
    //     void SetFrameRateMult();
    //     EXItemAnimator* GetAnimator();
    //     EXSwooshSys* InitWeaponSwoosh();
    //     void AutoWeaponSwoosh();
    //     /* vtable[37] */ virtual void UpdateWeaponSwoosh();
    //     void KillWeaponSwoosh();
    //     void KillAllSwoosh();
    //     EXHeadTracking* LookAt();
    //     EXHeadTracking* HeadtrackingOff();
    //     EXHeadTracking* OverrideHeadtracking();
    //     void SetLookAtLimits();
    //     void SetLookAtSpeed();
    //     /* vtable[38] */ virtual SEComms* AddComms();
    //     /* vtable[39] */ virtual void RemoveComms();
    //     void Comms();
    //     SEComms* Comms();
    //     void Shout(XSEItemHandler_Base*, int, void);
    //     void Ping();
    //     void PingHash();
    //     void PingLink();
    //     void PingLinks();
    //     void PingFamily(XSEItemHandler_Base*, int, void);
    //     void SendPacket();
    //     void SendPacket();
    //     void SendPacketLink();
    //     void SendPacketLink();
    //     void SendPacketLinks();
    //     void SendPacketLinks();
    //     void ReturnPacket();
    //     void DeletePacket();
    //     SEComms_packet* CreatePacket();
    //     /* vtable[40] */ virtual void DoCommsEvent();
    //     EXItemAnimator* AddShadow();
    //     Bool SetShadowLayer();
    //     /* vtable[41] */ virtual void DoShadowCast();
    //     void RemoveShadow();
    //     void CalcShadowThisFame();
    //     void StartContouredShadowUpdate();
    //     void StopContouredShadowUpdate();
    //     /* vtable[42] */ virtual RCode Init();
    //     /* vtable[14] */ virtual RCode InitialiseStart();
    //     /* vtable[17] */ virtual RCode Update();
    //     /* vtable[43] */ virtual RCode GeneratorTrigger();
    //     /* vtable[13] */ virtual RCode v_TriggerUpdateActivated();
    //     void InitMIPScale();
    //     Bool InitMIPScaleOFFOnly();
    //     void SetMIPScaleOn();
    //     void SetMIPScaleOff();
    //     /* vtable[44] */ virtual Bool DoMIPScale();
    //     /* vtable[45] */ virtual void ChangeEntity();
    //     XItemPhysics* SetupPhysics();
    //     XItemTerrainRotPhysics* SetupPhysics();
    //     void KillPhysics();
    //     XItemPhysics* SetCollisionFlags();
    //     XItemPhysics* ClrCollisionFlags();
    //     XItemPhysics* SetThrust();
    //     XItemPhysics* SetGravity();
    //     void EnableMapCollision();
    //     void DisableMapCollision();
    //     s8 GetPhysicsLayer();
    //     s8 GetShadowLayer();
    //     s32 InitPhysics();
    //     void AddToBreath();
    //     void RemoveFromBreath();
    //     void CheckBreath();
    //     /* vtable[46] */ virtual Bool TestBreathType();
    //     int VunerableToPlayer();
    //     int VunerableToWeapon();
    //     int VunerableTo();
    //     /* vtable[47] */ virtual Bool TestPlayerCollide();
    //     /* vtable[48] */ virtual s32 PlayerCollide();
    //     /* vtable[49] */ virtual Bool TestPlayerAttack();
    //     /* vtable[50] */ virtual s32 PlayerAttack();
    //     /* vtable[51] */ virtual void MissileHitPlayer();
    //     /* vtable[52] */ virtual Bool TestBeam();
    //     /* vtable[53] */ virtual void SetFrozen();
    //     /* vtable[54] */ virtual void SetUnFrozen();
    //     /* vtable[55] */ virtual void SetFrozenSmash();
    //     /* vtable[56] */ virtual void SetSmash(XSEItemHandler_Base*, int, void);
    //     /* vtable[57] */ virtual void SetElectrocuted(XSEItemHandler_Base*, int, void);
    //     /* vtable[58] */ virtual void SetWatered(XSEItemHandler_Base*, int, void);
    //     /* vtable[59] */ virtual Bool Frozen();
    //     /* vtable[60] */ virtual void Smash();
    //     /* vtable[61] */ virtual Bool Electrocuted();
    //     /* vtable[62] */ virtual Bool Watered();
    //     /* vtable[63] */ virtual void InitElectrocute();
    //     /* vtable[64] */ virtual void StopElectrocute();
    //     /* vtable[65] */ virtual void UpdateElectrocute();
    //     /* vtable[66] */ virtual void InitWatered();
    //     /* vtable[67] */ virtual void StopWatered();
    //     /* vtable[68] */ virtual void UpdateWatered();
    //     /* vtable[69] */ virtual void ProjectileCallback(XSEItemHandler_Base*, int, void);
    //     /* vtable[70] */ virtual Bool DoCharredEfect();
    //     /* vtable[71] */ virtual void SetCharred();
    //     /* vtable[72] */ virtual void UpdateCharred();
    //     /* vtable[73] */ virtual void StopCharred();
    //     /* vtable[74] */ virtual void EnableBlinkyVision();
    //     Bool HaveMultipleDatums();
    //     /* vtable[75] */ virtual Bool InitBodyCollisionDatumInfo();
    //     Bool RE_InitBodyCollisionDatumInfo();
    //     /* vtable[76] */ virtual Bool GetBodyCollisionData();
    //     void EnableBodyCollision();
    //     void DisableBodyCollision();
    //     /* vtable[20] */ virtual void DrawBodyCollision();
    //     Bool InitHeadDatumInfo();
    //     Bool GetHeadDatumPosition();
    //     float GetHeight();
    //     /* vtable[77] */ virtual Bool DoCollision();
    //     /* vtable[78] */ virtual Bool DoCollision();
    //     void OverrideStaticCollision();
    //     void ShowCollisions();
    //     Bool TestPlayer();
    //     /* vtable[79] */ virtual void DoBeamCallBack();
    //     EXItemRender_SkinAnim* AddFlameGloSkin();
    //     void DeleteFlameGloSkin();
    //     /* vtable[80] */ virtual void SetFlameGlo();
    //     /* vtable[81] */ virtual void UpdateFlameGlo();
    //     void StopFlameGlo();
    //     EXItemAnimator_Entity* AddFlameGloEntity();
    //     void DeleteFlameGloEntity();
    //     /* vtable[82] */ virtual void SetFlameGloEntity();
    //     /* vtable[83] */ virtual void UpdateFlameGloEntity();
    //     void StopFlameGloEntity();
    //     /* vtable[84] */ virtual void InitLighting();
    //     /* vtable[85] */ virtual void SetLighting();
    //     /* vtable[86] */ virtual void SetLighting();
    //     void CopyLighting();
    //     void PreserveAmbient();
    //     void SetAmbient();
    //     void SetAmbient();
    //     void RestoreAmbient();
    //     void ApplyLighting();
    //     void ApplyLighting();
    //     void SetLightingFromMap();
    //     /* vtable[87] */ virtual Bool ReleaseMyGems();
    //     Bool GetGemGeneratePos();
    //     PlayerPickups* CreatedPickup();
    //     SXI_PathPolyZone* AddZone();
    //     Bool BASIC_AddAbility();
    //     void BASIC_RemoveAbility();
    //     void BASIC_Update();
    //     void BASIC_SetWaitState(XSEItemHandler_Base*, int, void);
    //     void BASIC_ReceiveMessage();
    //     void BASIC_SetYesNoResult();
    //     /* vtable[88] */ virtual Bool BASIC_Waiting();
    //     /* vtable[89] */ virtual void BASICcmd_ForceTalk();
    //     /* vtable[90] */ virtual void BASICcmd_TalkIndicator();
    //     void BASICcmd_TalkCamera();
    //     void BASICcmd_HeroToTalkDist();
    //     void BASICcmd_HeroToLinkedPoint();
    //     void BASICcmd_HeroToPath();
    //     /* vtable[91] */ virtual s32 BASICcmd_GetDistanceToPlayer();
    //     /* vtable[92] */ virtual void BASICcmd_TalkToPlayer(XSEItemHandler_Base*, int, void);
    //     /* vtable[93] */ virtual void BASICcmd_PrintMessage();
    //     void BASICcmd_KillMessage();
    //     /* vtable[94] */ virtual void BASICcmd_YesNoBox();
    //     /* vtable[95] */ virtual s32 BASICcmd_IsFacingPlayer();
    //     /* vtable[96] */ virtual void BASICcmd_TurnAndFacePlayer();
    //     /* vtable[97] */ virtual s32 BASICcmd_GetNumberOfPathNodes();
    //     /* vtable[98] */ virtual s32 BASICcmd_GetDistanceToPathNode();
    //     /* vtable[99] */ virtual void BASICcmd_TurnToPathNode(XSEItemHandler_Base*, int, void);
    //     /* vtable[100] */ virtual Bool BASICcmd_WalkToPoint();
    //     /* vtable[101] */ virtual void BASICcmd_StopMoving();
    //     /* vtable[102] */ virtual void BASICcmd_React(XSEItemHandler_Base*, int, void);
    //     void BASICcmd_SendTo();
    //     void BASICcmd_SendToAll(XSEItemHandler_Base*, int, void);
    //     /* vtable[103] */ virtual void BASICcmd_HeadTrack(XSEItemHandler_Base*, int, void);
    //     void BASICcmd_SetObjective();
    //     void BASICcmd_ClearObjective();
    //     Bool BASICcmd_GetObjective();
    //     /* vtable[104] */ virtual void BASICcmd_SetAnim();
    //     /* vtable[105] */ virtual void BASICcmd_SetAnimDepth(XSEItemHandler_Base*, int, void);
    //     /* vtable[106] */ virtual void BASICcmd_SetNextAnim();
    //     /* vtable[107] */ virtual void BASICcmd_PlayCutscene();
    //     /* vtable[108] */ virtual void BASICcmd_PlayCutsceneWithTriggers();
    //     Bool BASICcmd_IsRestartPointVisited();
    //     Bool BASICcmd_IsRestartPointSet();
    //     void BASICcmd_SetRestartPoint();
    //     void BASICcmd_Camera_Store();
    //     void BASICcmd_Camera_Restore();
    //     void BASICcmd_Camera_ModeScriptPath();
    //     /* vtable[109] */ virtual void BASICcmd_Suicide();
    //     /* vtable[110] */ virtual void BASICcmd_Stall();
    //     void BASICcmd_PlaySample();
    //     /* vtable[111] */ virtual void BASICcmd_PlayScript();
    //     /* vtable[112] */ virtual void BASICcmd_PauseScript();
    //     /* vtable[113] */ virtual void BASICcmd_ResumeScript();
    //     /* vtable[114] */ virtual void BASICcmd_KillScript();
    //     void BASICcmd_SetEntityState();
    //     void BASICcmd_LoadHero();
    //     void BASICcmd_UnloadHero();
    //     Bool BASICcmd_IsHeroLoaded();
    //     void BASICcmd_ChangeHero();
    //     s32 BASICcmd_HeroCharacter();
    //     void BASICcmd_LoadFile();
    //     void BASICcmd_UnloadFile();
    //     Bool BASICcmd_IsFileLoaded();
    //     /* vtable[115] */ virtual void BASICcmd_Visibility(XSEItemHandler_Base*, int, void);
    //     void BASICcmd_PutHeroHere();
    //     void BASICcmd_GiveGemsToHero();
    //     void BASICcmd_TakeGemsFromHero();
    //     s32 BASICcmd_HowManyGems();
    //     void BASICcmd_GiveEggToHero();
    //     void BASICcmd_TakeEggFromHero();
    //     s32 BASICcmd_HowManyEggs();
    //     void BASICcmd_GiveLightGemsToHero();
    //     void BASICcmd_TakeLightGemsFromHero();
    //     s32 BASICcmd_HowManyLightGems();
    //     void BASICcmd_VisuallyGiveDragonEgg();
    //     void BASICcmd_VisuallyGiveLightGem();
    //     /* vtable[116] */ virtual void BASICcmd_Zoopoo();
    //     void BASICcmd_SetPanelClockTime();
    //     void BASICcmd_PanelClock();
    //     void BASICcmd_AddPanelClockTime();
    //     void BASICcmd_SubPanelClockTime();
    //     void BASICcmd_MapPlacementOn();
    //     void BASICcmd_MapPlacementOff();
    //     void BASICcmd_GameTimeout();
    //     void BASICcmd_HeroVisible();
    //     void BASICcmd_SparxVisible();
    //     void BASICcmd_GotoMap();
    //     void BASICcmd_LoadMap();
    //     void BASICcmd_CloseMap();
    //     bool BASICcmd_IsMapLoaded();
    //     void BASICcmd_SparxChat();
    //     void BASICcmd_MoveSparxAlongPath();
    //     void BASICcmd_LetsGoShopping();
    //     void BASICcmd_MapFadePause();
    //     void BASICcmd_LoadCutsceneFiles();
    //     void BASICcmd_UnloadCutsceneFiles();
    //     Bool BASICcmd_AreCutsceneFilesLoaded();
    //     void BASICcmd_RestartMap();
    //     Bool BASICcmd_TempGetState();
    //     void BASICcmd_TempCommand();
    //     void BASICcmd_LockControls();
    //     s32 BASICcmd_IsSafeToTalk();
    //     void BASICcmd_ProgressCounter(XSEItemHandler_Base*, int, void);
    //     void BASICcmd_SetProgress(XSEItemHandler_Base*, int, void);
    //     void BASICcmd_SetMaxProgress(XSEItemHandler_Base*, int, void);
    //     void BASICcmd_IncProgress(XSEItemHandler_Base*, int, void);
    //     s32 BASICcmd_GetProgress();
    //     void BASICcmd_GiveLockPicksToHero();
    //     void BASICcmd_TakeLockPicksFromHero();
    //     s32 BASICcmd_HowManyLockPicks();
    //     bool BASICcmd_IsThereANewShopItem();
    //     void BASICcmd_FadeDown(XSEItemHandler_Base*, int, void);
    //     void BASICcmd_FadeUp(XSEItemHandler_Base*, int, void);
    //     /* vtable[117] */ virtual void BASICcmd_PreventTalk(XSEItemHandler_Base*, int, void);
    //     s32 BASICcmd_HeroStatus();
    //     /* vtable[118] */ virtual void KillCutscene();
    //     /* vtable[119] */ virtual bool PlayCutscene();
    //     /* vtable[120] */ virtual bool IsPlayingCutscene();
    //     /* vtable[6] */ virtual u32 DoScriptCmdEvent();
    //     bool DoCommonScriptCmdEvents();
    //     /* vtable[25] */ virtual void v_ScriptCmd_TEXT();
    //     /* vtable[27] */ virtual void v_DoScriptCmd_Delete();
    //     /* vtable[28] */ virtual void v_DoScriptCmd_PostCreateCamera();
    //     /* vtable[121] */ virtual void SetVisibility();
    //     XSEItemHandler_CutScene* CreateCutSceneHandler();
    //     void AddParticleCollision();
    //     void RemoveParticleCollision();
};

#endif
