#ifndef EXWND_H
#define EXWND_H

#include <types.h>
#include <EngineX/EXList.h>
#include <EngineX/EXRect.h>
#include <EngineX/EXVector.h>
#include <EngineX/EXFlagTemplate.h>
#include <EngineX/EXRGB.h>

struct EXWnd;

// TODO: Fill out struct
struct EXBaseWnd : /* 0x000 */ EXDListItem
{ // 0x138
protected:
    /* 0x008 */ EXWnd* m_pParent;
    /* 0x00c */ EXDList m_Children;
    /* 0x014 */ EXRect m_Rect;
    /* 0x024 */ EXRect m_MinRect;
    /* 0x034 */ EXRect m_PrimRect;
    /* 0x044 */ EXRect m_PrimClipRect;
    /* 0x054 */ EXRect m_Sprite2DClip;
    /* 0x064 */ EXVector2 m_Origin;
    /* 0x06c */ EXFlag32 m_Flags;
    /* 0x070 */ EXFlag32 m_Effects;
    /* 0x074 */ RGBA m_BkColor;
    /* 0x078 */ RGBA m_BorderCol;
    /* 0x07c */ RGBA m_FBorderCol;
    /* 0x080 */ RGBA m_FontColor;
    /* 0x084 */ RGBA m_GSFogColor;
    /* 0x088 */ Bool m_NoiseBlendMode;
    /* 0x089 */ Bool m_DoneInitUpdate;
    /* 0x08a */ Bool m_HasMovieFinished;
    /* 0x08b */ Bool m_TexCapRequested;
    // /* 0x08c */ EXTexture* m_pTexCapTexture;
    /* 0x090 */ u16* m_pDbgText;
    /* 0x094 */ u16 m_DbgColor;
    /* 0x096 */ u16 m_DbgWidth;
    /* 0x098 */ u16 m_DbgHeight;
    /* 0x09c */ EXPoint m_DbgPos;
    // /* 0x0a4 */ EXGeoFont* m_pFont;
    // /* 0x0a8 */ EXTexture* m_pFontTexture;
    // /* 0x0ac */ EXTexture* m_pSprite2DTexture;
    // /* 0x0b0 */ EXPtrArray<unsigned char> m_DebugItems;
    // /* 0x0c0 */ EXPtrArray<unsigned char> m_Sprite2DData;
    // /* 0x0d0 */ EXParticleSysMgr* m_pParticleSysMgr;
    // /* 0x0d4 */ EXSwooshSysMgr* m_pSwooshSysMgr;
    // /* 0x0d8 */ EXMenu* m_pMenu;
    // /* 0x0dc */ EXInstanceManager* m_pInstanceManager;
    /* 0x0e0 */ u32 m_FocusBlurFactor;
    /* 0x0e4 */ u32 m_GlowColorMask;
    /* 0x0e8 */ u32 m_InverseColorMask;
    /* 0x0ec */ float m_GlowIntensity;
    /* 0x0f0 */ float m_FocusBlurDistance;
    /* 0x0f4 */ float m_MotionBlurFactor;
    /* 0x0f8 */ float m_InverseColorFactor;
    /* 0x0fc */ EXRectf m_MotionBlurSampleRect;
    /* 0x10c */ EXRectf m_MotionBlurDrawRect;
    // /* 0x11c */ EXTexture* m_pMotionBlurTex;
    /* 0x120 */ float m_NoiseIntensity;
    /* 0x124 */ float m_fNoiseTextureSampleWidth;
    /* 0x128 */ float m_fNoiseTextureSampleHeight;
    /* 0x12c */ RGBA m_BloomColor;

private:
    // /* 0x130 */ EXItemEnvView* m_pItemEnvView;

public:
    // /* 0x134 */ __vtbl_ptr_type* $vf2768;

    // EXBaseWnd& operator=();
    EXBaseWnd();
    // EXBaseWnd();
    // /* vtable[1] */ virtual EXBaseWnd(EXBaseWnd*, int, void);
    void FlushMem();
    void DeleteMem();
    void SetRect();
    void SetMinRect();
    // void SetRect();
    // void SetMinRect();
    EXRect& Rect();
    EXRect& PrimRect();
    EXRect& PrimClipRect();
    void SetOrigin();
    void SetOriginToCentre();
    EXVector2& Origin();
    EXFlag32& Flags();
    // EXFlag32& Flags();
    EXFlag32& Effects();
    // EXFlag32& Effects();
    RGBA BkColor();
    void SetBkColor();
    // EXMenu* Menu();
    void SetMenu();
    EXWnd* Parent();
    void SetParent();
    EXWnd* AddChild();
    void DelChild();
    void HideChild();
    Bool IsChild();
    EXWnd* FirstChild();
    EXWnd* LastChild();
    EXWnd* ContainsPrimPoint();
    EXWnd* ContainsDispPoint();
    /* vtable[2] */ virtual EXVector WndToPrim();
    // /* vtable[3] */ virtual EXVector2 WndToPrim();
    // /* vtable[4] */ virtual EXPoint WndToPrim();
    /* vtable[5] */ virtual EXVector PrimToWnd();
    // /* vtable[6] */ virtual EXVector2 PrimToWnd();
    // /* vtable[7] */ virtual EXPoint PrimToWnd();
    void SetFocusBlurFactor();
    void SetFocusBlurDistance();
    u32 GetFocusBlurFactor();
    float GetFocusBlurDistance();
    void SetGlowIntensity();
    void SetGlowColorMask();
    float GetGlowIntensity();
    u32 GetGlowColorMask();
    void SetMotionBlurFactor();
    float GetMotionBlurFactor();
    void SetMotionBlurSampleRect();
    EXRectf& GetMotionBlurSampleRect();
    void SetMotionBlurDrawRect();
    EXRectf& GetMotionBlurDrawRect();
    void SetNoiseBlendMode();
    Bool NoiseBlendMode();
    void SetNoiseIntensity();
    float GetNoiseIntensity();
    void SetNoiseTextureSampleWidth();
    float GetNoiseTextureSampleWidth();
    void SetNoiseTextureSampleHeight();
    float GetNoiseTextureSampleHeight();
    void SetInverseColorFactor();
    void SetInverseColorMask();
    float InverseColorFactor();
    u32 InverseColorMask();
    void SetGSFogColor();
    RGBA GSFogColor();
    void SetBloomColor();
    RGBA BloomColor();
    Bool RequestTextureCapture();
    void DbgClear();
    void SetDbgPos();
    void SetDbgPosPixels();
    u16 DbgCol();
    u16 DbgRow();
    void DbgPrint();
    void DbgScroll();
    u16 DbgWidth();
    u16 DbgHeight();
    void CreateDbgMem();
    void DeleteDbgMem();
    void CalcPrimRects();
    /* vtable[8] */ virtual Bool UpdateWindow();
    /* vtable[9] */ virtual Bool InitialUpdate();
    /* vtable[10] */ virtual Bool Update();
    /* vtable[11] */ virtual void DrawWindowShadow();
    /* vtable[12] */ virtual void BeginDrawShadow();
    /* vtable[13] */ virtual void DrawShadow();
    /* vtable[14] */ virtual void EndDrawShadow();
    /* vtable[15] */ virtual Bool DrawWindow();
    /* vtable[16] */ virtual void BeginDraw();
    /* vtable[17] */ virtual Bool Draw();
    /* vtable[18] */ virtual void EndDraw();
    /* vtable[19] */ virtual void DeleteRenderMem();
    Bool IsAtFront();
    Bool IsAtBack();
    Bool HasFocus();
    Bool IsVisible();
    /* vtable[20] */ virtual void Close();
    /* vtable[21] */ virtual void ButtonDown();
    /* vtable[22] */ virtual void ButtonUp();
    /* vtable[23] */ virtual void MouseMove();
    /* vtable[24] */ virtual void KeyDown();
    /* vtable[25] */ virtual void KeyUp();
    /* vtable[26] */ virtual void Char();
    /* vtable[27] */ virtual Bool MenuSelect();
    /* vtable[28] */ virtual void DrawLine();
    /* vtable[29] */ virtual void DrawLines();
    // /* vtable[30] */ virtual void DrawLines();
    /* vtable[31] */ virtual void SetTriFanBlendMode();
    /* vtable[32] */ virtual void SetTriFanZMode();
    /* vtable[33] */ virtual void SelectTriFanTexture();
    /* vtable[34] */ virtual void DrawTriFan();
    /* vtable[35] */ virtual void SetTriStripBlendMode();
    /* vtable[36] */ virtual void SetTriStripZMode();
    /* vtable[37] */ virtual void SelectTriStripTexture();
    /* vtable[38] */ virtual void DrawTriStrip();
    /* vtable[39] */ virtual void _SetSprite2DBlendMode();
    void SetSprite2DBlendMode();
    /* vtable[40] */ virtual void _SelectSprite2DTexture();
    void SelectSprite2DTexture();
    // void SelectSprite2DTexture();
    /* vtable[41] */ virtual void _SetSprite2DClipRect();
    void SetSprite2DClipRect();
    // void SetSprite2DClipRect();
    void ResetSprite2DClipRect();
    EXRect Sprite2DClipRect();
    /* vtable[42] */ virtual void _DrawSprite2D();
    void DrawSprite2D();
    // void DrawSprite2D();
    // void DrawSprite2D();
    // void DrawSprite2D();
    // void DrawSprite2D();
    // /* vtable[43] */ virtual void _DrawSprite2D();
    // void DrawSprite2D();
    // /* vtable[44] */ virtual void _DrawSprite2D();
    // void DrawSprite2D();
    void DeleteSprite2DData();
    void SelectFont();
    // void SelectFont();
    RGBA FontColor();
    void SetFontColor();
    EXPoint FontTextSize();
    // EXPoint FontTextSize();
    // EXPoint FontTextSize();
    // EXPoint FontTextSize();
    EXPoint FontCharSize();
    // EXPoint FontCharSize();
    u16 FontCharWidth();
    u16 FontCharHeight();
    void FontPrint();
    // void FontPrint();
    // void FontPrint();
    // void FontPrint();
    // void FontPrint();
    // void FontPrint();
    // void FontPrint();
    // void FontPrint();
    // void FontPrint();
    // void FontPrint();
    // EXParticleSysMgr* ParticleSysMgr();
    void DeleteParticleSysMem();
    void DeleteAllParticleSystems();
    void StopParticleUpdateAndRender();
    void PauseParticleSystems();
    // EXSwooshSysMgr* SwooshSysMgr();
    void DeleteSwooshSysMem();
    void DeleteAllSwooshSystems();
    void StopSwooshUpdateAndRender();
    void PauseSwooshSystems();
    // EXInstanceManager* GetInstanceManager();
    void DeleteInstanceManager();
    void RegisterItemEnvView();
    void ReleaseItemEnvView();
    Bool UpdateItemEnvView();
    Bool RenderItemEnvView();
    // EXItemEnvView* ItemEnvView();
    /* vtable[45] */ virtual void MovieOpen();
    /* vtable[46] */ virtual void MovieUpdate();
    /* vtable[47] */ virtual void MovieRender();
    /* vtable[48] */ virtual void MovieClose();
    Bool HasMovieFinished();
    void SetHasMovieFinished();
    char* Debug_Name();
    void Debug_SetName();
    void Debug_SetObjectToWorld();
    void Debug_SetObjectToWorld0();
    void _Debug_Line2D();
    void Debug_Line2D();
    // void Debug_Line2D();
    void _Debug_Rect2D();
    void Debug_Rect2D();
    // void Debug_Rect2D();
    // void Debug_Rect2D();
    void _Debug_SolidRect2D();
    void Debug_SolidRect2D();
    // void Debug_SolidRect2D();
    // void Debug_SolidRect2D();
    void Debug_Line3D();
    void Debug_Arrow3D();
    void Debug_TriLine3D();
    void Debug_QuadLine3D();
    void Debug_Plane3D();
    void Debug_BoxLine3D();
    void Debug_Marker3D();
    void Debug_CircleX3D();
    void Debug_CircleY3D();
    void Debug_CircleZ3D();
    void Debug_Sphere3D();
    void Debug_Cone3D();
    void Debug_BoundBox3D();
    // void Debug_Sphere3D();
    void Debug_Cylinder3D();
    void Debug_Capsule3D();
    void Debug_Lozenge3D();
    void Debug_Box3D();
    void Debug_Tetrahedron3D();
    void Debug_Pyramid3D();
    void Debug_Octahedron3D();
    void Debug_Icosahedron3D();
    void Debug_Dodecahedron3D();
    void Debug_Text3D();
    // void Debug_Text3D();
    void Debug_DeleteDebugItemData();

protected:
    void Debug_ClearDebugItemData();
    void DrawDebugItems();

public:
    void GetStringProperties();
    // void GetStringProperties();

protected:
    void ClearSprite2DData();
    void AddSprite2DData();
    void* AllocSprite2DData();
    /* vtable[49] */ virtual void RebuildBloom();
    static Bool CalcChildPrimRects(/* parameters unknown */);
    static Bool UpdateChild(/* parameters unknown */);
    static Bool DrawChild(/* parameters unknown */);
    void RenderFont();
    // void RenderFont();
    void CalculateAlignment();
};

#endif // EXWND_H
