y

		
main/SETrigger_ctors.cpp:
	.text       start:0x80379F00 end:0x8037A7FC

Weird split ranges that havent been resolved yet.
	0x80379f00 - 0x8037abac // seems to be a lot of functions from random files??? Maybe weak from something?
	XSEItem_Default has one function in it? The current theory is the rest is ctors and dtors


EngineX\EXWndDebug.cpp:

EngineX\EXWndSprite.cpp:

EngineX\EXWndText.cpp:

EngineX\EXWString.cpp:

EngineX\EXPhysicsSphere.cpp:

EngineX\EXPhysicsSoft.cpp:

EngineX\GC\EngineX.cpp:

EngineX\EXArray.cpp:

EngineX\EXDbgfont.cpp:

EngineX\EXEffectsSys.cpp:

EngineX\EXGeoGrabpoint.cpp:

EngineX\EXGeoInstance.cpp:

EngineX\EXGeoTexture.cpp:


EngineX\EXItemAnimator_Camera.cpp:

EngineX\EXItemAnimator_Collision.cpp:

EngineX\EXRect.cpp:

EngineX\GC\GCGeoEntity_Instance.cpp:

EngineX\GC\GCGeoTexture.cpp:
